enc_id = '00DbfmGl7Nj5lDWlm4qXHyTZU5X21iDID7cg=='
password = ''
salt = 'vmqse2'
key_pair = [
    [
    57,
    168,
    38,
    25,
    236,
    126,
    29,
    166,
    198,
    211,
    118,
    132,
    54,
    167,
    197,
    228,
    253,
    239,
    212,
    23,
    27,
    221,
    41,
    123,
    245,
    70,
    65,
    44,
    15,
    251,
    78,
    2,
    9,
    224,
    149,
    178,
    11,
    96,
    240,
    45,
    52,
    63,
    8,
    165,
    49,
    204,
    72,
    178,
    185,
    33,
    165,
    103,
    16,
    135,
    80,
    67,
    215,
    2,
    205,
    212,
    41,
    165,
    37,
    246,
],
    [
    9,
    224,
    149,
    178,
    11,
    96,
    240,
    45,
    52,
    63,
    8,
    165,
    49,
    204,
    72,
    178,
    185,
    33,
    165,
    103,
    16,
    135,
    80,
    67,
    215,
    2,
    205,
    212,
    41,
    165,
    37,
    246,
],
]
key_confirmed = true

[keys_confirmed]
rs-sg = true
rs-ny = true
rs-cn = true
